# Generated by Django 2.2 on 2026-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
